digix/digix_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from django.views.defaults import page_not_found

urlpatterns = [
    path('built_in_admin/', admin.site.urls),
    path('admin/',include('digix_admin.urls')),
    path('',include('user.urls')),
    path('product/',include('products.urls'))
]

# Define a custom handler404 view and specify the custom template for 404 errors
handler404 = 'user.views.custom_404_view'  # Replace 'yourapp.views.custom_404_view' with the actual view function you want to use for custom handling of 404 errors


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

digix/products/urls.py
from django.urls import path

from . import views

app_name='product'

urlpatterns=[
path('category/',views.get_all_category,name='all_category'),
path('product/',views.get_all_products,name='all_products'),
path('variant/',views.get_all_variants,name='all_variants'),
path('variant_with_image/',views.get_variant_data,name="variant_with_image")


]

digix/user/urls.py
from django.urls import path
from . import views

#order views
from orders.views import order_confirm,order_success,return_order,cancel_order,generate_pdf,generate_order_detail_pdf
#review views 
from review.views import add_review,delete_review,update_review



app_name='user'

urlpatterns =[

#home page
path('',views.index,name='index'),

#get all products
path('all_products/',views.category_display_all_products,name='all_products'),
#get products on category or brand name
  path('all_products/<str:category>/', views.category_display_all_products, name='category_display_all_products'),
    #get products on category or brand name on filter value
    path('all_products/<str:category>/<str:sort_option>/', views.category_display_all_products, name='category_display_all_products'),
    #path('all_products/<str:category>/<str:brand>/<str:sort_option>/', views.category_display_all_products, name='category_display_all_products'),


#get specafic product
path('product/<int:id>/',views.product,name="product"),

#get variants for a particular product
path('product/simillar_variants/<int:id>/',views.get_variants),

#user login , sign up , logout

path('user_sign_in/',views.user_sign_in,name='user_sign_in'),


path('user_sign_up/',views.user_sign_up,name='user_sign_up'),
path('user_logout/',views.user_logout,name='user_logout'),


#user sign up , fetch , dyanmic field value checking
path('user_sign_up_value/',views.user_sign_up_value,name='user_sign_up_value'),

#search results
path('search_results/',views.search,name='search'),

#search json
 path('search_variants/', views.search_variants, name='search_variants'),

#get all users
path('user/get_all_users/',views.get_all_users),
path('user/unblock/<int:id>/',views.user_unblock),
path('user/block/<int:id>/',views.user_block),

#forgot password
path('forgot_password/',views.forgot_password,name='forgot_password'),
#verify otp
path('verify_otp/',views.verify_otp,name='verify_otp'),

#user password update
path('user_password_update/<int:id>/',views.user_password_update,name='user_password_update'),

#otp resend , update
path('otp_update/',views.otp_update,name='otp_update'),



#profile page
path('profile/',views.user_profile,name='user_profile'),



#wishlist page
path('wishlist/',views.user_wishlist,name='user_wishlist'),

#checkout page
path('checkout/',views.user_checkout,name='user_checkout'),
path('checkout/<str:coupoun_applied>/<int:applied_coupoun>/<str:updated_cart_amount>/',views.user_checkout,name='user_checkout'),


#user profile views
path('dashboard/',views.user_profile_dashboard,name='user_profile_dashboard'),
path('orders/',views.user_profile_order,name='user_profile_orders'),
path('address/',views.user_profile_address,name='user_profile_address'),

#view handle update user details except password update
path('account_details',views.user_profile_account_details,name='user_profile_account_details'),

#update password
path('profile_password_update/',views.user_profile_password_update,name='user_profile_password_update'),

#password change validating form
 path('account_password_update/', views.user_account_password_update, name='user_account_password_update'),

#user sign up , fetch , dyanmic field value checking
path('user_account_details_update_value/',views.user_account_details_update_value,name='user_account_details_update_value'),


#add new address 
path('add_new_address/',views.add_new_address,name='add_new_address'),
#update address
path('update_address/<int:id>/',views.update_address,name='update_address'),
#delete address
path('delete_address/<int:id>/',views.delete_address,name='delete_address'),
#set default address
path('default_address/<int:id>/',views.default_address,name='default_address'),

#checking user authenticated , already in wishlist  and already in cart
path('user_logged_in_status/',views.user_logged_in_status),
path('variant_in_wishlist_status/',views.variant_in_wishlist_status),

#product adding in wish list
path('add_to_wishlist/<int:id>/',views.add_to_wishlist,name='add_to_wishlist'),
#remove product from wishlist
path('remove_from_wishlist/<int:id>/',views.remove_from_wishlist,name='remove_from_wishlist'),
#wishlist product count
path('wishlist_product_count/',views.wishlist_product_count,),

#cart
#cart page
path('cart/',views.user_cart,name='user_cart'),
#cart product count
path('variant_in_cart_status/',views.variant_in_cart_status),

#product adding in wish list
path('add_to_cart/<int:id>/',views.add_to_cart,name='add_to_cart'),
#remove product from cart
path('remove_from_cart/<int:id>/',views.remove_from_cart,name='remove_from_cart'),
#cart product count
path('cart_product_count/',views.cart_product_count,),
#cart product qty update
path('cart_variant_qty_update/<int:id>/<int:quantity>/',views.cart_variant_qty_update),

#cart status
path('user_cart_status/',views.user_cart_status),


#add new address 
path('add_new_address_cart/',views.add_new_address_cart,name='add_new_address_cart'),
#update address
path('update_address_cart/<int:id>/',views.update_address_cart,name='update_address_cart'),
#delete address
path('delete_address_cart/<int:id>/',views.delete_address_cart,name='delete_address_cart'),
#set default address
path('default_address_cart/<int:id>/',views.default_address_cart,name='default_address_cart'),

#check variant qty for checkout page
path('get_variant_stock/<int:variant_id>/',views.get_variant_stock),


#orders
#order confirm
path('order_confirm/',order_confirm),
#order success 
path('order_success/<str:order_num>/',order_success),
#cancel order
path('cancel_order/<int:order_id>/<int:variant_id>/',cancel_order,name='cancel_order'),
#return order
path('return_order/<int:id>/<str:reason>/',return_order,name='return_order'),
#order detail
path('order_detail/<int:order_id>/<int:variant_id>/',views.order_detail,name='order_detail'),

#generate pdf
 path('generate_pdf/<str:order_num>/', generate_pdf, name='generate_pdf'),

 #single order pdf generate
 path('order_detail_pdf/<int:order_id>/<int:variant_id>/',generate_order_detail_pdf,name='generate_order_detail_pdf'),

 #get rasor pay instance
 path('razor_pay_instance/',views.razor_pay_instance),

 #review 
 path('add_review/<int:variant_id>/',add_review,name="add_review"),

 path('delete_review/<int:id>/<int:variant_id>/',delete_review,name='delete_review'),

 path('update_review/<int:id>/<int:variant_id>/',update_review),

#user profile wallet
path('user_wallet/',views.user_wallet,name='user_wallet'),

#current order status,
path('current_order_status/<int:order_id>/',views.current_order_status,),

#apply coupoun,
path('apply_coupoun/<int:id>/',views.apply_coupoun,name='apply_coupoun'),


]

digix/products/models.py
from django.db import models
import random


#function to generate a random number for each object
#because for security reasons we can't display the orginal id of product or variant or category
def generate_random_8_digit_number():
    # Generate an 8-digit random number
    min_value = 10000000  # Smallest 8-digit number
    max_value = 99999999  # Largest 8-digit number
    return random.randint(min_value, max_value)



#category model
class Category(models.Model):

    name = models.CharField(max_length=30,unique=True)
    rand_id = models.BigIntegerField(default=generate_random_8_digit_number,unique=True)
    is_availble = models.BooleanField(default=False)

    def __str__(self) -> str:
        return self.name
    


#product model
class Product(models.Model):

    name=models.CharField(max_length=30,unique=True)
    category = models.ForeignKey(Category,related_name='category_products',on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    brand = models.CharField(max_length=30)
    rand_id = models.BigIntegerField(default=generate_random_8_digit_number,unique=True)

    def __str__(self) -> str:
        return self.name
    

class Variant(models.Model):

    tv_mount_choices = [
    (' ', ' '),  # Empty or default choice
    ("wall mount", "Wall Mount"),
    ("table mount", "Table Mount")
]

    name = models.CharField(max_length=200,unique=True)
    rand_id = models.BigIntegerField(default=generate_random_8_digit_number,unique=True)
    product = models.ForeignKey(Product,on_delete=models.CASCADE,related_name='product_variants')
    ram = models.PositiveIntegerField()
    storage = models.PositiveIntegerField()
    color = models.CharField(max_length=20)

    mr_price = models.DecimalField(max_digits=8,decimal_places=2)
    selling_price = models.DecimalField(max_digits=8,decimal_places=2)
    #when adding the offer to variant that offer price will be in the selling_price and the
    #amount on the selling_price will be on the price_before_offer
    #when offer ends the selling_price will be set to the previous price
    price_before_offer = models.DecimalField(max_digits=8,decimal_places=2,default=0)

    stock = models.PositiveIntegerField()
    is_available= models.BooleanField(default=False)
    screen_resolution = models.DecimalField(max_digits=5,decimal_places=2,blank=True,null=True)

    no_of_usb_ports = models.PositiveIntegerField(blank=True,null=True)
    no_of_hdmi_ports = models.PositiveIntegerField(blank=True,null=True)
    tv_mount = models.CharField(max_length=30,blank=True,null=True)
    
    description=models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.product} {self.name}'
       
    def save(self, *args, **kwargs):
        # Log the variant name and selling price before saving
        print(f"Saving variant: {self.name}, Selling Price: {self.selling_price}")
        
        # Call the parent class's save method to perform the actual save operation
        super(Variant, self).save(*args, **kwargs)

#image for a variant
class Variant_Images(models.Model):
    variant = models.ForeignKey(Variant,on_delete=models.CASCADE,related_name="variant_images")
    image=models.ImageField(upload_to='product_images/',null=True,blank=True)
    def __str__(self) -> str:
        return self.variant
    

digix/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import hashlib
#import Variant from products
from products.models import Variant



#custom user model with phone field

class CustomUser(AbstractUser):

    phone = models.CharField(max_length=10,unique=True)


    # Add related_name arguments to avoid reverse accessor clash
    groups = models.ManyToManyField(
        'auth.Group',
        related_name='custom_users',
        blank=True,
    )
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        related_name='custom_users',
        blank=True,
    )

    def __str__(self):
        return self.username
    def make_password(self, raw_password):
        
        #hashing logic
        
        salt = 'abcdefghijk'  # Add a unique salt value

        hashed_password = hashlib.sha256((salt + raw_password).encode()).hexdigest()
        print('hashed')
        return hashed_password
    
#checking password when loging 
#the input password will be hashed and checked with the user object password hashed value

    def check_password(self, raw_password):
        hashed_input_password = self.make_password(raw_password)
        print('checking hashed password')
        return self.password == hashed_input_password
    
    
    

''' 
After this now we have to set in settings that our CustomUser want to be used as
the User model in our django project . So now go to settings.py and add
AUTH_USER_MODEL = 'user.CustomUser'

'''



class ShippingAddress(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="address",null=True,blank=True)
    address = models.CharField(max_length=100,null=True,blank=True)
    city = models.CharField(max_length=50,null=True,blank=True)
    state = models.CharField(max_length=50,null=True,blank=True)
    zip_code = models.CharField(max_length=50,null=True,blank=True)
    country = models.CharField(max_length=50, default='India',blank=True)
    default_address = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username+""+self.address


    class Meta:
        verbose_name_plural = "Shipping Address"





class Wishlist(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="wishlist",null=True,blank=True)
    variant = models.ForeignKey(Variant,on_delete=models.CASCADE,related_name='variant')

    def __str__(self):
        return self.user.username+""+self.address


    class Meta:
        verbose_name_plural = "Wishlist"

digix/user/forms.py
from . models import CustomUser,ShippingAddress
from django.forms import ModelForm


class UserCreationForm(ModelForm):
    class Meta:
        model=CustomUser
        fields=['username','phone','email','password']


class ShippingAddressForm(ModelForm):
    class Meta:
        model = ShippingAddress
        fields = '__all__'

digix/products/views.py
from django.http import JsonResponse
from django.shortcuts import redirect, render
from . models import Category,Product,Variant



# these functions return the json response for data table 

def get_all_category(request):
    data= Category.objects.all().values()
    print(list(data))
    return JsonResponse({'data': list(data)})

def get_all_products(request):
    data = Product.objects.all().values('id', 'name', 'category__name','brand')
    
    
    return JsonResponse({'data': list(data)})

def get_all_variants(request):
    data= Variant.objects.all().values('id','name','product__name','ram','storage','color','mr_price','selling_price','stock','is_available')
    return JsonResponse({'data': list(data)})

def get_variant_data(request):
    

    variants = Variant.objects.all().prefetch_related('variant_images')
    
    data = []
    
    for variant in variants:
        variant_data = {
            'id': variant.id,
            'name': variant.name,
            'product_name': variant.product.name,
            'ram': variant.ram,
            'storage': variant.storage,
            'color': variant.color,
            'mr_price': variant.mr_price,
            'selling_price': variant.selling_price,
            'stock': variant.stock,
            'is_available': variant.is_available,
        }
        
        # Collect image URLs for the variant
        image_urls = [image.image.url for image in variant.variant_images.all()]
        
        variant_data['images'] = image_urls
        data.append(variant_data)
    
    return JsonResponse({'data': data})

digix/user/templates/user_app/orders.html
{% extends 'user_app/user_base.html' %}"
{% load static %}
{% block title %}Profile Orders{% endblock %}

{% block importantcss %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<style src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/css/bootstrap.min.css"></style>
<style src="https://cdn.datatables.net/1.13.6/css/dataTables.bootstrap5.min.css"></style>
{% endblock %}
{% block body %}

        <main class="main">
        	<div class="page-header text-center" >
        		<div class="container">
        			<h1 class="page-title">My Account</h1>
        		</div><!-- End .container -->
        	</div><!-- End .page-header -->
           

            <div class="page-content">
            	<div class="dashboard">
	                <div class="container">
	                	<div class="row">
	                		<aside class="col-md-4 col-lg-3">
	                			<ul class="nav nav-dashboard flex-column mb-3 mb-md-0" role="tablist">
								    <li class="nav-item">
								        <a class="nav-link " id="tab-dashboard-link"  href="{% url 'user:user_profile_dashboard' %}" >Dashboard</a>
								    </li>
								    <li class="nav-item">
								        <a class="nav-link active" id="tab-orders-link"  href="{% url 'user:user_profile_orders' %}" >Orders</a>
								    </li>
								    
								    <li class="nav-item">
								        <a class="nav-link" id="tab-address-link"  href="{% url 'user:user_profile_address' %}" >Addresses</a>
								    </li>
								    <li class="nav-item">
								        <a class="nav-link " id="tab-account-link"  href="{% url 'user:user_profile_account_details' %}" >Account Details</a>
								    </li>
									<li class="nav-item">
                                        <a class="nav-link " id="tab-account-link"  href="{% url 'user:user_wallet' %}" >Wallet</a>
                                    </li>
									
								    
								</ul>
	                		</aside><!-- End .col-lg-3 -->

	                		<div class="col-md-8 col-lg-9">
	                			<div class="tab-content">
									


									
									{% if order_count > 0 %}

									<div class="row">
										<table id="example" class="table table-striped" style="width:100%;font-size:12px;">
											<thead>
												<tr>
													<th></th>
													<th>Order number</th>
													<th>Product Name</th>
													<th>Date</th>
													<th>Status</th>
													
												</tr>
											</thead>
											<tbody>
												{% for order in user_orders %}
												{% for order_item in order.order_items.all %}
												
												<tr>
													
													<td style="width:100px;">
														{% with variant_image=order_item.variant.variant_images.first %}
														<img src="{{ variant_image.image.url }}" alt="{{ order_item.variant.name }} Image" style="width:99px;height:101px;">
													{% endwith %}
													</td>
													<td style="font-weight:500;">{{ order.order_num }}</td>

													<td style="font-weight:500;"> <a href="{% url 'user:order_detail' order.id order_item.variant.id %}" class="text-dark text-decoration-none">{{ order_item.variant.name }}</a></td>
													<td>{{ order.date_created }}</td>
													<td class="text-dark" style="font-weight:500;">{% if order_item.order_status == 'order_pending' %}
														Order Pending
														{% elif order_item.order_status == 'returned' %}
														Order Returned
														{% elif order_item.order_status == 'order_confirmed' %}
														Order Confirmed
														{% elif order_item.order_status == 'shipped' %}
														Order Shipped
														{% elif order_item.order_status == 'delivered' %}
														Delivered
														{% elif order_item.order_status == 'waiting_for_approval' %}
                   										 Waiting for Approval
														{% else %}
														Cancelled
													{% endif %}</td>
											
												</tr>
												
												{% endfor %}
												{% endfor %}
											</tbody>
											
										</table>
									</div>


									{% else %}


									<div class="row" >
								    	<p>No order has been made yet.</p>
								    	<a href="{% url 'user:index' %}" class="btn btn-outline-primary-2"><span>GO SHOP</span><i class="icon-long-arrow-right"></i></a>
								    </div><!-- .End .tab-pane -->


								{% endif %}


									
									

									
								   
								   


										

								</div>
	                		</div><!-- End .col-lg-9 -->
	                	</div><!-- End .row -->
	                </div><!-- End .container -->
                </div><!-- End .dashboard -->
            </div><!-- End .page-content -->
        </main><!-- End .main -->

       {% endblock %}

	   {% block importantjs %}
	   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
	   <script src="https://code.jquery.com/jquery-3.7.0.js"></script>
	   <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
	   <script src="https://cdn.datatables.net/1.13.6/js/dataTables.bootstrap5.min.js"></script>
	   <script>
        new DataTable('#example');
		
		a_tags =document.getElementsByTagName('a')

// Get all elements with class 'widget' and 'content-widget'
var widgetElements = document.querySelectorAll('.widget-list');

// Loop through each 'widget' and 'content-widget' element
widgetElements.forEach(function(element) {
 // Get all <a> tags inside the current 'widget' or 'content-widget' element
 var aTags = element.querySelectorAll('a');
 
 // Loop through each <a> tag inside this element and apply your styling
 aTags.forEach(function(aTag) {
   // Apply your styling to the <a> tag, for example:
   aTag.style.color = '#333333';
   aTag.style.textDecoration = 'none';
 });
});
    </script>
{% endblock %}

digix/user/templates/user_app/user_account_details.html
{% extends 'user_app/user_base.html' %}"
{% load static %}
{% block title %}Profile{% endblock %}

{% block body %}

        <main class="main">
        	<div class="page-header text-center" >
        		<div class="container">
        			<h1 class="page-title">My Account</h1>
        		</div><!-- End .container -->
        	</div><!-- End .page-header -->
           

            <div class="page-content">
            	<div class="dashboard">
	                <div class="container">
	                	<div class="row">
	                		<aside class="col-md-4 col-lg-3">
	                			<ul class="nav nav-dashboard flex-column mb-3 mb-md-0" role="tablist">
								    <li class="nav-item">
								        <a class="nav-link" id="tab-dashboard-link"  href="{% url 'user:user_profile_dashboard' %}" >Dashboard</a>
								    </li>
								    <li class="nav-item">
								        <a class="nav-link" id="tab-orders-link"  href="{% url 'user:user_profile_orders' %}" >Orders</a>
								    </li>
								    
								    <li class="nav-item">
								        <a class="nav-link" id="tab-address-link"  href="{% url 'user:user_profile_address' %}" >Addresses</a>
								    </li>
								    <li class="nav-item">
								        <a class="nav-link active" id="tab-account-link"  href="{% url 'user:user_profile_account_details' %}" >Account Details</a>
								    </li>
									<li class="nav-item">
										<a class="nav-link " id="tab-account-link"  href="{% url 'user:user_wallet' %}" >Wallet</a>
									</li>
		
								    
								</ul>
	                		</aside><!-- End .col-lg-3 -->

	                		<div class="col-md-8 col-lg-9">
	                			<div class="tab-content">
									

								    <div >

										{% if password_change and password_input %}

										<form method="POST">
												{% csrf_token %}
											<div class="row">
			                					<div class="col-sm-6">
			                						<label>Password *</label>
			                						<input type="password" class="form-control" name="password1">
			                					</div><!-- End .col-sm-6 -->

			                					<div class="col-sm-6">
			                						<label>Confirm Password *</label>
			                						<input type="password" class="form-control" name="password2">
			                					</div><!-- End .col-sm-6 -->
			                				</div><!-- End .row -->
											<button type="submit" class="btn btn-dark mt-5">
			                					<span>Update password</span>
			            						<i class="icon-long-arrow-right"></i>
			                				</button>
										</form>

										{% elif password_change %}

										<form method="POST">

											{% csrf_token %}

											<div class="row">
												<span id="id_bs" style="display:none;" >{{request.user.id}}</span>
			                					<div class="col-sm-6">
			                						<label>Enter Otp *</label>

													<div class="d-flex justify-content-center">
														<div class="d-flex w-50" style="border:1px solid #333333;">
							
															<input type="text" class="form-control h-100 m-0 otp-input" maxlength="1" id="exampleInputOtp"   aria-describedby="emailHelp"   onfocus="this.style.borderColor = 'green';this.style.borderWidth = '2px';" 
														onblur="this.style.borderColor = '#ced4da';" name="otp1">
							
														<input type="text" class="form-control h-100 m-0 otp-input" maxlength="1" id="exampleInputOtp"   aria-describedby="emailHelp"   onfocus="this.style.borderColor = 'green';this.style.borderWidth = '2px';" 
												  onblur="this.style.borderColor = '#ced4da';" name="otp2">
							
												  <input type="text" class="form-control h-100 m-0 otp-input" maxlength="1" id="exampleInputOtp"   aria-describedby="emailHelp"   onfocus="this.style.borderColor = 'green';this.style.borderWidth = '2px';" 
												  onblur="this.style.borderColor = '#ced4da';" name="otp3">
							
												  <input type="text" class="form-control h-100 m-0 otp-input" maxlength="1" id="exampleInputOtp"   aria-describedby="emailHelp"   onfocus="this.style.borderColor = 'green';this.style.borderWidth = '2px';" 
												  onblur="this.style.borderColor = '#ced4da';" name="otp4">
														</div>
													</div>
												</div><!-- End .col-sm-6 -->

			                				</div><!-- End .row -->

											{% if resend_btn %}
		            						<div class="text-start mt-2">
												<a href="{% url 'user:user_profile_password_update' %}">Resend Otp</a>
											</div>
											{% endif %}

		                					<button type="submit" class="btn btn-dark mt-5">
			                					<span>Verify Otp</span>
			            						<i class="icon-long-arrow-right"></i>
			                				</button>
										</form>


										{% else %}

										<form method="POST" id="user_account_update_form">

											{% csrf_token %}

			                				<div class="row">
												<span id="id_bs" style="display:none;" >{{request.user.id}}</span>
			                					<div class="col-sm-6">
			                						<label>Username *</label>

			                						<input type="text" id='id_username' class="form-control" name="username" value="{{ username }}" >
													<div class="error-container" id="username-error"></div>
												</div><!-- End .col-sm-6 -->

			                					<div class="col-sm-6">
			                						<label>Email *</label>
			                						<input type="email" id="id_email" class="form-control" name="email" value="{{ email }}"> 
													<div class="error-container" id="email-error"></div>
			                					</div><!-- End .col-sm-6 -->

												<div class="col-sm-6">
			                						<label>Phone *</label>
			                						<input type="text" class="form-control" name="phone" id='id_phone' value="{{ phone }}" >
													<div class="error-container" id="phone-error"></div>
           											 <div class="error-container" id="phone1-error"></div>
			                					</div><!-- End .col-sm-6 -->

			                				</div><!-- End .row -->

		            						

		                					<button type="submit" class="btn btn-dark mt-5">
			                					<span>SAVE CHANGES</span>
			            						<i class="icon-long-arrow-right"></i>
			                				</button>


											
			                			</form>


										{% endif %}
								    	{% if not password_change %}
										<a class="btn btn-dark mt-2" href="{% url 'user:user_profile_password_update' %}">Change Password</a>
										{% endif %}
										<div class="text-center">
											{% if messages %}
											<div class="alert {% if message.tags == 'error' %}alert-danger{% elif message.tags == 'success' %}alert-success{% endif %}">
												{% for message in messages %}
												<p {% if message.tags == 'error' %} class="text-danger" {% elif message.tags == 'success' %} class="text-success" {% endif %} >{{ message }}</p>
												{% endfor %}
											</div>
											{% endif %}
											</div>


								    </div><!-- .End .tab-pane -->


								</div>
	                		</div><!-- End .col-lg-9 -->
	                	</div><!-- End .row -->
	                </div><!-- End .container -->
                </div><!-- End .dashboard -->
            </div><!-- End .page-content -->
        </main><!-- End .main -->

       {% endblock %}

digix/user/templates/user_app/user_phone_otp.html
{% extends 'user_app/user_base.html' %}
{% load static %}
{% block title %} Otp{% endblock %}
{% block body %}
<div id='example1' style="background-image: url('{% static 'login/background.jpg' %}');">
    <div  class="container h-75 mb-4" >
    
        <div class="row mb-4">
           <div class="col-5 mb-4"></div>
            <div class="col-4 mt-5 p-2 bg-light  text-center user_login_div" >
                <div class="d-flex justify-content-center">
                    <img src="{% static 'logo.jpg' %}" class="img-fluid" alt="Digix logo" style="width:10rem;height:10rem;">
                </div>
                <form class="mb-4" method="POSt">
                    
                    <div class="form-group mt-5 px-4">
                        <div class="text-start"><label for="exampleInputphone_number">Phone Number</label></div>
                      
                      <input type="text" class="form-control p-2" id="exampleInputphone_number"   aria-describedby="emailHelp" placeholder="Enter Phone Number"  onfocus="this.style.borderColor = 'green';" 
                      onblur="this.style.borderColor = '#ced4da';" name="phone_number">
                     
                    </div>
                    
                    
                    <button type="submit" class="btn btn-primary p-3 mb-3" style="background:#333333;">Send Otp</button>
                  </form>
            </div>
            
        </div>
    </div>
</div>
{% endblock %}