digix/digix_admin/urls.py
from django.urls import path

from . import views
app_name= 'digix_admin'
urlpatterns = [
    path('',views.admin_home,name='admin_home'),

    path('admin_logout/',views.admin_logout,name='admin_logout'),

    path('admin_login/',views.admin_login,name='admin_login'),

    path('add_category/',views.add_category,name='add_category'),

    path('all_category/',views.all_category,name='all_category'),

    path('add_product/',views.add_product,name='add_product'),

    path('all_products/',views.all_products,name='all_products'),

    path('add_variant/',views.add_variant,name='add_variant'),

    path('all_variants/',views.all_variants,name='all_variants'),

    path('category_delete/<int:id>/',views.delete_category),

    path('category_update/<int:id>/',views.category_update),

    path('product_delete/<int:id>/',views.delete_product),

    path('product_update/<int:id>/',views.product_update),

    path('variant_delete/<int:id>/',views.delete_variant),

    path('variant_update/<int:id>/',views.variant_update),

    path('all_users/',views.all_users,name='all_users'),

    path('all_orders/',views.orders,name='orders'),
    
    path('change_order_status/<int:id>/<str:value>/',views.change_order_status,name='change_order_status'),

    path('returns/',views.all_returns,name='returns'),

    path('return_order/<int:id>/',views.return_order,name='return_order'),

    path('return_reason_update/<str:order_num>/<int:variant_id>/<int:return_order_id>/',views.return_reason_update,name='return_reason_update'),

    path('accept_return_reason/<int:id>/',views.accept_return_reason,name='accept_return_reason'),

    #coupoun
    path('all_coupouns/',views.all_coupouns,name='all_coupouns'),

    path('add_coupoun/',views.add_coupoun,name='add_coupoun'),

    #get all variants,
    path('get_all_variants/',views.get_all_variants),
    path('edit_coupoun/<int:id>/',views.edit_coupoun,name='edit_coupoun'),

    #get all offers,
    path('all_offers/',views.all_offers,name='all_offers'),
    path('add_offer/',views.add_offer,name='add_offer'),
    path('edit_offer/<int:id>/',views.edit_offer,name='edit_offer'),

    path('change_offer_status/<int:id>/',views.change_offer_status,name='change_offer_status'),

    #chart
    path('get_order_data/',views.get_order_data),
    path('chart_order_status/',views.chart_order_status),
    #download report,   
    path('download_report/',views.download_report,name='download_report'),
    

]

digix/digix_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from django.views.defaults import page_not_found

urlpatterns = [
    path('built_in_admin/', admin.site.urls),
    path('admin/',include('digix_admin.urls')),
    path('',include('user.urls')),
    path('product/',include('products.urls'))
]

# Define a custom handler404 view and specify the custom template for 404 errors
handler404 = 'user.views.custom_404_view'  # Replace 'yourapp.views.custom_404_view' with the actual view function you want to use for custom handling of 404 errors


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

digix/products/urls.py
from django.urls import path

from . import views

app_name='product'

urlpatterns=[
path('category/',views.get_all_category,name='all_category'),
path('product/',views.get_all_products,name='all_products'),
path('variant/',views.get_all_variants,name='all_variants'),
path('variant_with_image/',views.get_variant_data,name="variant_with_image")


]

digix/user/urls.py
from django.urls import path
from . import views

#order views
from orders.views import order_confirm,order_success,return_order,cancel_order,generate_pdf,generate_order_detail_pdf
#review views 
from review.views import add_review,delete_review,update_review



app_name='user'

urlpatterns =[

#home page
path('',views.index,name='index'),

#get all products
path('all_products/',views.category_display_all_products,name='all_products'),
#get products on category or brand name
  path('all_products/<str:category>/', views.category_display_all_products, name='category_display_all_products'),
    #get products on category or brand name on filter value
    path('all_products/<str:category>/<str:sort_option>/', views.category_display_all_products, name='category_display_all_products'),
    #path('all_products/<str:category>/<str:brand>/<str:sort_option>/', views.category_display_all_products, name='category_display_all_products'),


#get specafic product
path('product/<int:id>/',views.product,name="product"),

#get variants for a particular product
path('product/simillar_variants/<int:id>/',views.get_variants),

#user login , sign up , logout

path('user_sign_in/',views.user_sign_in,name='user_sign_in'),


path('user_sign_up/',views.user_sign_up,name='user_sign_up'),
path('user_logout/',views.user_logout,name='user_logout'),


#user sign up , fetch , dyanmic field value checking
path('user_sign_up_value/',views.user_sign_up_value,name='user_sign_up_value'),

#search results
path('search_results/',views.search,name='search'),

#search json
 path('search_variants/', views.search_variants, name='search_variants'),

#get all users
path('user/get_all_users/',views.get_all_users),
path('user/unblock/<int:id>/',views.user_unblock),
path('user/block/<int:id>/',views.user_block),

#forgot password
path('forgot_password/',views.forgot_password,name='forgot_password'),
#verify otp
path('verify_otp/',views.verify_otp,name='verify_otp'),

#user password update
path('user_password_update/<int:id>/',views.user_password_update,name='user_password_update'),

#otp resend , update
path('otp_update/',views.otp_update,name='otp_update'),



#profile page
path('profile/',views.user_profile,name='user_profile'),



#wishlist page
path('wishlist/',views.user_wishlist,name='user_wishlist'),

#checkout page
path('checkout/',views.user_checkout,name='user_checkout'),
path('checkout/<str:coupoun_applied>/<int:applied_coupoun>/<str:updated_cart_amount>/',views.user_checkout,name='user_checkout'),


#user profile views
path('dashboard/',views.user_profile_dashboard,name='user_profile_dashboard'),
path('orders/',views.user_profile_order,name='user_profile_orders'),
path('address/',views.user_profile_address,name='user_profile_address'),

#view handle update user details except password update
path('account_details',views.user_profile_account_details,name='user_profile_account_details'),

#update password
path('profile_password_update/',views.user_profile_password_update,name='user_profile_password_update'),

#password change validating form
 path('account_password_update/', views.user_account_password_update, name='user_account_password_update'),

#user sign up , fetch , dyanmic field value checking
path('user_account_details_update_value/',views.user_account_details_update_value,name='user_account_details_update_value'),


#add new address 
path('add_new_address/',views.add_new_address,name='add_new_address'),
#update address
path('update_address/<int:id>/',views.update_address,name='update_address'),
#delete address
path('delete_address/<int:id>/',views.delete_address,name='delete_address'),
#set default address
path('default_address/<int:id>/',views.default_address,name='default_address'),

#checking user authenticated , already in wishlist  and already in cart
path('user_logged_in_status/',views.user_logged_in_status),
path('variant_in_wishlist_status/',views.variant_in_wishlist_status),

#product adding in wish list
path('add_to_wishlist/<int:id>/',views.add_to_wishlist,name='add_to_wishlist'),
#remove product from wishlist
path('remove_from_wishlist/<int:id>/',views.remove_from_wishlist,name='remove_from_wishlist'),
#wishlist product count
path('wishlist_product_count/',views.wishlist_product_count,),

#cart
#cart page
path('cart/',views.user_cart,name='user_cart'),
#cart product count
path('variant_in_cart_status/',views.variant_in_cart_status),

#product adding in wish list
path('add_to_cart/<int:id>/',views.add_to_cart,name='add_to_cart'),
#remove product from cart
path('remove_from_cart/<int:id>/',views.remove_from_cart,name='remove_from_cart'),
#cart product count
path('cart_product_count/',views.cart_product_count,),
#cart product qty update
path('cart_variant_qty_update/<int:id>/<int:quantity>/',views.cart_variant_qty_update),

#cart status
path('user_cart_status/',views.user_cart_status),


#add new address 
path('add_new_address_cart/',views.add_new_address_cart,name='add_new_address_cart'),
#update address
path('update_address_cart/<int:id>/',views.update_address_cart,name='update_address_cart'),
#delete address
path('delete_address_cart/<int:id>/',views.delete_address_cart,name='delete_address_cart'),
#set default address
path('default_address_cart/<int:id>/',views.default_address_cart,name='default_address_cart'),

#check variant qty for checkout page
path('get_variant_stock/<int:variant_id>/',views.get_variant_stock),


#orders
#order confirm
path('order_confirm/',order_confirm),
#order success 
path('order_success/<str:order_num>/',order_success),
#cancel order
path('cancel_order/<int:order_id>/<int:variant_id>/',cancel_order,name='cancel_order'),
#return order
path('return_order/<int:id>/<str:reason>/',return_order,name='return_order'),
#order detail
path('order_detail/<int:order_id>/<int:variant_id>/',views.order_detail,name='order_detail'),

#generate pdf
 path('generate_pdf/<str:order_num>/', generate_pdf, name='generate_pdf'),

 #single order pdf generate
 path('order_detail_pdf/<int:order_id>/<int:variant_id>/',generate_order_detail_pdf,name='generate_order_detail_pdf'),

 #get rasor pay instance
 path('razor_pay_instance/',views.razor_pay_instance),

 #review 
 path('add_review/<int:variant_id>/',add_review,name="add_review"),

 path('delete_review/<int:id>/<int:variant_id>/',delete_review,name='delete_review'),

 path('update_review/<int:id>/<int:variant_id>/',update_review),

#user profile wallet
path('user_wallet/',views.user_wallet,name='user_wallet'),

#current order status,
path('current_order_status/<int:order_id>/',views.current_order_status,),

#apply coupoun,
path('apply_coupoun/<int:id>/',views.apply_coupoun,name='apply_coupoun'),


]

digix/digix_admin/models.py
from django.db import models

# Create your models here.

digix/products/models.py
from django.db import models
import random


#function to generate a random number for each object
#because for security reasons we can't display the orginal id of product or variant or category
def generate_random_8_digit_number():
    # Generate an 8-digit random number
    min_value = 10000000  # Smallest 8-digit number
    max_value = 99999999  # Largest 8-digit number
    return random.randint(min_value, max_value)



#category model
class Category(models.Model):

    name = models.CharField(max_length=30,unique=True)
    rand_id = models.BigIntegerField(default=generate_random_8_digit_number,unique=True)
    is_availble = models.BooleanField(default=False)

    def __str__(self) -> str:
        return self.name
    


#product model
class Product(models.Model):

    name=models.CharField(max_length=30,unique=True)
    category = models.ForeignKey(Category,related_name='category_products',on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    brand = models.CharField(max_length=30)
    rand_id = models.BigIntegerField(default=generate_random_8_digit_number,unique=True)

    def __str__(self) -> str:
        return self.name
    

class Variant(models.Model):

    tv_mount_choices = [
    (' ', ' '),  # Empty or default choice
    ("wall mount", "Wall Mount"),
    ("table mount", "Table Mount")
]

    name = models.CharField(max_length=200,unique=True)
    rand_id = models.BigIntegerField(default=generate_random_8_digit_number,unique=True)
    product = models.ForeignKey(Product,on_delete=models.CASCADE,related_name='product_variants')
    ram = models.PositiveIntegerField()
    storage = models.PositiveIntegerField()
    color = models.CharField(max_length=20)

    mr_price = models.DecimalField(max_digits=8,decimal_places=2)
    selling_price = models.DecimalField(max_digits=8,decimal_places=2)
    #when adding the offer to variant that offer price will be in the selling_price and the
    #amount on the selling_price will be on the price_before_offer
    #when offer ends the selling_price will be set to the previous price
    price_before_offer = models.DecimalField(max_digits=8,decimal_places=2,default=0)

    stock = models.PositiveIntegerField()
    is_available= models.BooleanField(default=False)
    screen_resolution = models.DecimalField(max_digits=5,decimal_places=2,blank=True,null=True)

    no_of_usb_ports = models.PositiveIntegerField(blank=True,null=True)
    no_of_hdmi_ports = models.PositiveIntegerField(blank=True,null=True)
    tv_mount = models.CharField(max_length=30,blank=True,null=True)
    
    description=models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.product} {self.name}'
       
    def save(self, *args, **kwargs):
        # Log the variant name and selling price before saving
        print(f"Saving variant: {self.name}, Selling Price: {self.selling_price}")
        
        # Call the parent class's save method to perform the actual save operation
        super(Variant, self).save(*args, **kwargs)

#image for a variant
class Variant_Images(models.Model):
    variant = models.ForeignKey(Variant,on_delete=models.CASCADE,related_name="variant_images")
    image=models.ImageField(upload_to='product_images/',null=True,blank=True)
    def __str__(self) -> str:
        return self.variant
    

digix/coupoun/forms.py
from django import forms
from . models import Coupons,Offers

class CoupounForm(forms.ModelForm):
    class Meta:
        model = Coupons
        fields = '__all__'
        widgets = {
            'valid_to': forms.DateInput(attrs={'type': 'date'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Customize labels for the form fields
        self.fields['code'].label = 'Coupon Code'
        self.fields['discount_percentage'].label = 'Discount Percentage'
        self.fields['cart_min_amount'].label = 'Minimum Cart Amount'
        self.fields['is_active'].label = 'Is Active'
        self.fields['is_deleted'].label = 'Is Deleted'
        self.fields['coupoun_type'].label = 'Coupon Type'
        self.fields['coupoun_applied_to'].label = 'Coupon Applied To'
        self.fields['count'].label = 'Count'
        self.fields['cart_max_amount'].label = 'Cart Maximum Amount'
        self.fields['discount_amount'].label = 'Discount Amount'

        # Make all fields not required
        for field_name, field in self.fields.items():
            field.required = False


class OfferForm(forms.ModelForm):
    class Meta:
        model = Offers
        fields = ['name',  'category', 'variant', 'discount_percentage', 'start_date', 'end_date']
        widgets = {
            'start_date': forms.DateInput(attrs={'type': 'date'}),
            'end_date': forms.DateInput(attrs={'type': 'date'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Customize labels for the form fields
        self.fields['name'].label = 'Offer Name'
        self.fields['variant'].label = 'Product Variant'
        self.fields['category'].label = 'Product Category'
        self.fields['discount_percentage'].label = 'Discount Percentage'
       
        self.fields['start_date'].label = 'Start Date'
        self.fields['end_date'].label = 'End Date'

        # Make all fields not required
        for field_name, field in self.fields.items():
            field.required = False

digix/user/forms.py
from . models import CustomUser,ShippingAddress
from django.forms import ModelForm


class UserCreationForm(ModelForm):
    class Meta:
        model=CustomUser
        fields=['username','phone','email','password']


class ShippingAddressForm(ModelForm):
    class Meta:
        model = ShippingAddress
        fields = '__all__'

digix/coupoun/views.py
from django.shortcuts import render

# Create your views here.

digix/products/views.py
from django.http import JsonResponse
from django.shortcuts import redirect, render
from . models import Category,Product,Variant



# these functions return the json response for data table 

def get_all_category(request):
    data= Category.objects.all().values()
    print(list(data))
    return JsonResponse({'data': list(data)})

def get_all_products(request):
    data = Product.objects.all().values('id', 'name', 'category__name','brand')
    
    
    return JsonResponse({'data': list(data)})

def get_all_variants(request):
    data= Variant.objects.all().values('id','name','product__name','ram','storage','color','mr_price','selling_price','stock','is_available')
    return JsonResponse({'data': list(data)})

def get_variant_data(request):
    

    variants = Variant.objects.all().prefetch_related('variant_images')
    
    data = []
    
    for variant in variants:
        variant_data = {
            'id': variant.id,
            'name': variant.name,
            'product_name': variant.product.name,
            'ram': variant.ram,
            'storage': variant.storage,
            'color': variant.color,
            'mr_price': variant.mr_price,
            'selling_price': variant.selling_price,
            'stock': variant.stock,
            'is_available': variant.is_available,
        }
        
        # Collect image URLs for the variant
        image_urls = [image.image.url for image in variant.variant_images.all()]
        
        variant_data['images'] = image_urls
        data.append(variant_data)
    
    return JsonResponse({'data': data})

digix/digix_admin/templates/digix_admin/header.html
{% load static %}

  <div class="container-fluid bg-light text-dark" id="going">
    <div class="row">
      <div class="col-12 p-2" style="background: #bab8b9;">
        <div class="d-flex mx-5 justify-content-between">

          <a href="{% url 'digix_admin:admin_home' %}" class="logo">
            <img src="{% static 'logo.jpg' %}" alt="DigiX Logo" width="135" height="105">
        </a>
          <a href="{% url 'digix_admin:admin_logout' %}" class="btn btn-danger mt-5">Log out</a>
          
        </div>
        <div class="mx-5 mt-3">
          <i class="bi bi-list text-dark mx-5 " style="font-size: 2rem;" onclick="myFunction()"></i>
        </div>
      </div>
    </div>
    <div class="row text-center" >
     
      
      <div class="col-2" id="nav-div" style="border-right:2px solid black;" >
        <ul class="nav" id="nav_ul" >
        
          <li class="nav-item menu-items ml-5 mb-5 mt-5">
            <a  class="btn mr-3 p-2 border-right-5 w-100 d-flex justify-content-center align-items-center text-black admin_side_a" href="{% url 'digix_admin:admin_home' %}" > <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-house-door-fill mr-2 text-black" viewBox="0 0 16 16">
              <path d="M6.5 14.5v-3.505c0-.245.25-.495.5-.495h2c.25 0 .5.25.5.5v3.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5Z"/>
            </svg>Home
            </a></li>
  
          <li class="nav-item menu-items ml-5 mb-5">
          <a  class="btn  mr-3 p-3 border-right-5 w-100 d-flex justify-content-center align-items-center text-black admin_side_a"" href="{% url 'digix_admin:all_category' %}" ><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi mr-2 text-black bi-bookmarks" viewBox="0 0 16 16">
            <path d="M2 4a2 2 0 0 1 2-2h6a2 2 0 0 1 2 2v11.5a.5.5 0 0 1-.777.416L7 13.101l-4.223 2.815A.5.5 0 0 1 2 15.5V4zm2-1a1 1 0 0 0-1 1v10.566l3.723-2.482a.5.5 0 0 1 .554 0L11 14.566V4a1 1 0 0 0-1-1H4z"/>
            <path d="M4.268 1H12a1 1 0 0 1 1 1v11.768l.223.148A.5.5 0 0 0 14 13.5V2a2 2 0 0 0-2-2H6a2 2 0 0 0-1.732 1z"/>
          </svg>Category
          </a></li>
  
          <li class="nav-item menu-items ml-5 mb-5">
            <a  class="btn  mr-3 p-3 border-right-5 w-100 d-flex justify-content-center align-items-center text-black admin_side_a"" href="{% url 'digix_admin:all_products' %}" ><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi mr-2 text-black bi-phone-vibrate" viewBox="0 0 16 16">
              <path d="M10 3a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h4zM6 2a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h4a2 2 0 0 0 2-2V4a2 2 0 0 0-2-2H6z"/>
              <path d="M8 12a1 1 0 1 0 0-2 1 1 0 0 0 0 2zM1.599 4.058a.5.5 0 0 1 .208.676A6.967 6.967 0 0 0 1 8c0 1.18.292 2.292.807 3.266a.5.5 0 0 1-.884.468A7.968 7.968 0 0 1 0 8c0-1.347.334-2.619.923-3.734a.5.5 0 0 1 .676-.208zm12.802 0a.5.5 0 0 1 .676.208A7.967 7.967 0 0 1 16 8a7.967 7.967 0 0 1-.923 3.734.5.5 0 0 1-.884-.468A6.967 6.967 0 0 0 15 8c0-1.18-.292-2.292-.807-3.266a.5.5 0 0 1 .208-.676zM3.057 5.534a.5.5 0 0 1 .284.648A4.986 4.986 0 0 0 3 8c0 .642.12 1.255.34 1.818a.5.5 0 1 1-.93.364A5.986 5.986 0 0 1 2 8c0-.769.145-1.505.41-2.182a.5.5 0 0 1 .647-.284zm9.886 0a.5.5 0 0 1 .648.284C13.855 6.495 14 7.231 14 8c0 .769-.145 1.505-.41 2.182a.5.5 0 0 1-.93-.364C12.88 9.255 13 8.642 13 8c0-.642-.12-1.255-.34-1.818a.5.5 0 0 1 .283-.648z"/>
            </svg>Product
            </a></li>
            <li class="nav-item menu-items ml-5 mb-5">
              <a  class="btn  mr-3 p-3 border-right-5 w-100 d-flex justify-content-center align-items-center text-black admin_side_a"" href="{% url 'digix_admin:all_variants' %}" >
                <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi mr-2 text-black bi-laptop" viewBox="0 0 16 16">
                  <path d="M13.5 3a.5.5 0 0 1 .5.5V11H2V3.5a.5.5 0 0 1 .5-.5h11zm-11-1A1.5 1.5 0 0 0 1 3.5V12h14V3.5A1.5 1.5 0 0 0 13.5 2h-11zM0 12.5h16a1.5 1.5 0 0 1-1.5 1.5h-13A1.5 1.5 0 0 1 0 12.5z"/>
                </svg>Variant
              </a></li>
  
              <li class="nav-item menu-items ml-5 mb-5">
                <a  class="btn  mr-3 p-3 border-right-5 w-100 d-flex justify-content-center align-items-center text-black admin_side_a"" href="{% url 'digix_admin:all_users' %}" >
                  <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi mr-2 text-black bi-person-fill" viewBox="0 0 16 16">
                    <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3Zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z"/>
                  </svg>Users
                </a></li>
  
                <li class="nav-item menu-items ml-5 mb-5">
                  <a  class="btn  mr-3 p-3 border-right-5 w-100 d-flex justify-content-center align-items-center text-black admin_side_a"" href="{% url 'digix_admin:orders' %}" >
                    <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi mr-2 text-black bi-cart-fill" viewBox="0 0 16 16">
                      <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                    </svg>Orders
                  </a></li>
                
                  <li class="nav-item menu-items ml-5 mb-5">
                    <a  class="btn  mr-3 p-3 border-right-5 w-100 d-flex justify-content-center align-items-center text-black admin_side_a"" href="{% url 'digix_admin:returns' %}" >
                      <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi mr-2 text-black bi-cart-fill" viewBox="0 0 16 16">
                        <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                      </svg>Returns
                    </a></li>
  
                <li class="nav-item menu-items ml-5 mb-5">
                  <a  class="btn  mr-3 p-3 border-right-5 w-100 d-flex justify-content-center align-items-center text-black admin_side_a"" href="{% url 'digix_admin:all_coupouns' %}" >
                    <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi mr-2 text-black bi-cart-fill" viewBox="0 0 16 16">
                      <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                    </svg>Coupouns
                  </a></li>
  
                  <li class="nav-item menu-items ml-5 mb-5">
                    <a  class="btn  mr-3 p-3 border-right-5 w-100 d-flex justify-content-center align-items-center text-black admin_side_a"" href="{% url 'digix_admin:all_offers' %}" >
                      <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi mr-2 text-black bi-cart-fill" viewBox="0 0 16 16">
                        <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                      </svg>Offers
                    </a></li>
                
  
  
  
  
        </ul>
      </div>
      <div class="col-9" id="digix-content-div">
        
      </div>
    </div>
  </div>
  
{% include 'digix_admin/footer.html' %}
  <div class="main-panel" id="main_panel_div"></div>

digix/digix_admin/templates/digix_admin/product.html
{% extends 'digix_admin/base.html' %}
{% load static %}

{% block title %}Products{% endblock %}

{% block body %}
   

<div class="content-wrapper" id="content_wrapper_div">
<div class="text-right m-3"><a class='btn btn-success p-3 add_btn' href="{% url 'digix_admin:add_product' %}">Add Product</a></div>

<table id="myTable2" class="cell-border hover order-column stripe row-border bg-light">

  <thead>
      <!-- really important when rendering button , an empty <td> want to be given else won't work --empty data table -->
      
          <td>Product</td> 
          <td>Category</td> 
          <td>Brand</td> 
          <td></td>
          <td></td>

  </thead>

  <!-- Your table content here -->
</table>


      </div>
</div>


{% endblock %}